// Presentation metadata only; colours and stitches come from the app itself.
#pragma once
struct catalogue_entry { const char *name, *match, *chart, *palette, *pattern; };
static const struct catalogue_entry catalogue[] = {
  { "Finder", "Finder", "atelier-finder", "Finder blue, ice blue, navy", "Blue checks with aligned knitted corners" },
  { "Microsoft Teams", "Microsoft Teams", "atelier-teams", "Violet, porcelain", "Soft porcelain zigzags on violet knit" },
  { "Claude", "Claude", "atelier-claude", "Apricot, vanilla", "Cream stars on apricot wool, no inner trim" },
  { "Codex", "Codex", "atelier-chatgpt", "Blue, cream", "Cream chevrons on blue knit, patterned corners" },
  { "Spotify", "Spotify", "atelier-spotify", "Leaf green, butter yellow", "Raised knitted checks, patterned corners" },
  { "Notion", "Notion", "atelier-notion", "Paper white, charcoal", "Raised ivory and charcoal knitted checks" },
  { "WhatsApp", "WhatsApp", "atelier-whatsapp", "Meadow, pistachio, pink", "Broad stripes with pink accents, green corners" },
  { "Figma", "Figma", "atelier-figma", "Mauve and pastel accents", "Playful colour blocks" },
  { "Google Chrome", "Google Chrome", "atelier-chrome", "Ivory, red, green, yellow, blue", "Ivory knit with colourful checks" },
  { "Paper", "Paper", "atelier-paper", "Paper blue, white, denim", "Layered sheet motifs" },
  { "ChatGPT", "ChatGPT", "atelier-chatgpt", "Blue, cream", "Cream chevrons on blue knit, patterned corners" },
  { "Grok Bot", "Grok Bot", "atelier-grok", "Charcoal, oatmeal, silver", "Framed stripes, matching knitted corners" },
  { "Discord", "Discord", "checker", "Blurple, warm white", "Mini checkerboard" },
  { "Granola", "Granola", "atelier-granola", "Deep grey, leaf green", "Grey and green stripes, patterned corners" },
  { "Ghostty", "ghostty", "atelier-ghostty", "Midnight, soft ivory", "Quiet ivory stripes" },
  { "Safari", "Safari", "atelier-safari", "Sky blue, porcelain, coral", "Compass diamonds" },
  { "Firefox", "Firefox", "atelier-firefox", "Violet, tangerine, golden peach", "Flame chevrons" },
  { "Slack", "Slack", "atelier-slack", "Aubergine, blue, mint, gold, pink", "Confetti crosses" },
  { "Zoom", "zoom.us", "atelier-zoom", "Cobalt, ice blue, white", "Linked little windows" },
  { "Telegram", "Telegram", "atelier-telegram", "Sky blue, white, glacier", "Folded diagonal ribbons" },
  { "Messages", "Messages", "atelier-messages", "Apple green, white, pale lime", "Scattered polka dots" },
  { "Mail", "Mail", "atelier-mail", "Azure, white, powder blue", "Envelope scallops" },
  { "Notes", "Notes", "atelier-notes", "Vanilla, golden yellow", "Ivory knit with a continuous curved golden cuff" },
  { "Calendar", "Calendar", "atelier-calendar", "Paper white, tomato", "White knit with a continuous curved red cuff" },
  { "Reminders", "Reminders", "atelier-reminders", "Paper, blue, coral, orange, grey", "Tiny task stitches" },
  { "Apple Music", "Music", "atelier-music", "Watermelon, ballet pink, cream", "Syncopated rose zigzags" },
  { "Photos", "Photos", "atelier-photos", "Cream and six petal colours", "Rainbow posies" },
  { "Preview", "Preview", "atelier-preview", "Denim, glacier, snow", "Alpine photo frames" },
  { "Microsoft Word", "Microsoft Word", "atelier-word", "Book blue, cornflower, paper", "Classic two-tone chevrons" },
  { "Microsoft Excel", "Microsoft Excel", "atelier-excel", "Forest, sage, pale mint", "Workbook windowpane" },
  { "Microsoft PowerPoint", "Microsoft PowerPoint", "atelier-powerpoint", "Terracotta, salmon, peach", "Nested presentation tiles" },
  { "Microsoft Outlook", "Microsoft Outlook", "atelier-outlook", "Outlook blue, sky, white", "Overlapping envelope checks" },
  { "VS Code", "Code", "atelier-vscode", "Code blue, deep ink, ice", "Angular linked ribbons" },
  { "Adobe Photoshop", "Adobe Photoshop", "atelier-photoshop", "Midnight, cyan, soft blue", "Pixel-frame checks" },
  { "Adobe Illustrator", "Adobe Illustrator", "atelier-illustrator", "Espresso, orange, apricot", "Warm rugby stripes" },
  { "Terminal", "Terminal", "atelier-terminal", "Charcoal green, soft sage", "Sage stripes with matching knitted corners" },
  { "Cursor", "Cursor", "atelier-cursor", "Warm charcoal, stone", "Soft stone zigzags on charcoal knit" },
  { "OpenCode", "OpenCode", "atelier-opencode", "Warm charcoal, oatmeal", "Offset oatmeal windowpanes on charcoal knit" },
  { "Beeper", "Beeper", "atelier-beeper", "Royal violet, alabaster, perfume", "Little speech bubbles on violet knit" },
  { "Willow Voice", "Willow Voice", "atelier-willow", "Pale lavender, willow indigo", "Little indigo willows on lavender knit" },
  { "Google Antigravity", "Antigravity", "atelier-antigravity", "Ink, lime, coral, electric blue", "Rainbow arches on ink knit" },
  { "YouTube Music", "YouTube Music", "atelier-ytmusic", "YouTube red, white, almost black", "Broad white stripes with a black pin on red knit" },
  { "Proton VPN", "ProtonVPN", "atelier-protonvpn", "Electric violet, white, mountain meadow", "White and meadow chevrons on violet knit" },
  { "Xcode", "Xcode", "atelier-xcode", "Xcode blue, graphite", "Quiet graphite stripes on blueprint knit" },
  { "App Store", "App Store", "atelier-appstore", "App Store blue, ice", "Ice checks on App Store blue knit" },
  { "Android Studio", "Android Studio", "atelier-androidstudio", "Studio blue, Android green", "Android green checks on studio blue knit" },
  { "System Settings", "System Settings", "atelier-settings", "Aluminum, graphite", "Quiet graphite stripes on aluminum knit" },
  { "Weather", "Weather", "atelier-weather", "Sky blue, cloud white, sun yellow", "Cloud-white and sun-yellow dots on sky knit" },
};
enum { CATALOGUE_COUNT = sizeof catalogue / sizeof catalogue[0] };
